### ISSUE TITLE
Adaptation for Mac OS

### ISSUE THREAD

**Issue by projetmbc** [minrk/clingkernel#12]
Hello.

How can I adapt your kernel so as to use it on a Mac ?

**Comment by minrk** [comment]
I'm not sure. I've only ever used it on a mac. The main thing was to set CLING_EXE environment variable to the location of my cling executable.

**Comment by projetmbc** [comment]
I have to wait so as to test on a Mac OS because CLING can't be compiled. I opened [an issue](https://github.com/vgvassilev/cling/issues/78) 12 days ago.

**Comment by minrk** [comment]
this is now part of cling
