### ISSUE TITLE
Kenel unable to start

### ISSUE THREAD

**Issue by kaback** [minrk/clingkernel#13]
I am using
XUbuntu 14.4

and
jupyter --version
4.0.6

I installed clang/cling using the build script from here:
https://root.cern.ch/cling-build-instructions

When starting jupyter notebook and selecting the C++ kernel, the kernel is unable to start. I get  the following error:

[I 22:37:24.716 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 6e3e3b60-2366-4531-a30a-6dc26ca176c0 restarted
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/kaback/GITROOT/clingkernel/clingkernel.py", line 18, in <module>
    from pexpect import replwrap, EOF
ImportError: cannot import name replwrap
[W 22:37:27.727 NotebookApp] KernelRestarter: restart failed

Am i doing something wrong?

**Comment by minrk** [comment]
Try:

    pip install --upgrade pexpect

**Comment by kaback** [comment]
This worked for me. Thanks!
