### ISSUE TITLE
missing 'path' module when starting C++ kernel

### ISSUE THREAD

**Issue by jbcoe** [minrk/clingkernel#2]
When I open a C++ notebook the kernel crashes with the following error:

    packages/ipykernel/connect.py", line 13, in <module>
        from IPython.paths import get_ipython_dir
    ImportError: No module named paths

I'm using ipykernel from: 
https://github.com/minrk/ipykernel

and IPython 3.1.

Can the README be updated with version requirements?

**Comment by WesternStar** [comment]
I have it up and running on a python3 virtualenv with these modules 
certifi (2015.4.28)
clingkernel (0.0.1)
decorator (3.4.2)
ipykernel (4.0.0.dev0, /home/alvin/.virtualenvs/jupyter/src/ipykernel)
ipython (4.0.0.dev0, /home/alvin/.virtualenvs/jupyter/src/ipython)
ipython-genutils (0.1.0)
Jinja2 (2.7.3)
jsonschema (2.4.0)
jupyter-client (4.0.0.dev0, /home/alvin/.virtualenvs/jupyter/src/jupyter-client)
jupyter-core (4.0.0.dev0, /home/alvin/.virtualenvs/jupyter/src/jupyter-core)
MarkupSafe (0.23)
mistune (0.5.1)
nbconvert (4.0.0.dev0, /home/alvin/.virtualenvs/jupyter/src/nbconvert)
nbformat (4.0.0.dev0, /home/alvin/.virtualenvs/jupyter/src/nbformat)
notebook (4.0.0.dev0, /home/alvin/programming/jupyter/notebook)
path.py (7.3)
pexpect (3.3)
pickleshare (0.5)
pip (6.1.1)
ptyprocess (0.5)
Pygments (2.0.2)
pyzmq (14.6.0)
setuptools (16.0)
simplegeneric (0.8.1)
terminado (0.5)
tornado (4.1)
traitlets (4.0.0.dev0, /home/alvin/.virtualenvs/jupyter/src/traitlets)

**Comment by jbcoe** [comment]
thanks
